name: basic_utils
description: Common util classes providing a solution for different situations.
version: 2.7.0
homepage: https://github.com/Ephenodrom/Dart-Basic-Utils
publish_to: https://pub.dartlang.org

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.13.0
  logging: ^1.0.0
  json_annotation: ^3.1.1
  pointycastle: ^3.0.0-nullsafety.2
  convert: ^2.1.1
  crypto: ^3.0.0


dev_dependencies:
  build_runner: ^1.10.7
  json_serializable: ^3.5.0
  pedantic: ^1.9.0
  test: ^1.6.0
